### PR TITLE
fix(charts): fix regression issues with charts layout and responsiveness

### LINKED ISSUE #644: Dashboard responsive charts layout issues on iPhone
We're still having issues with responsive charts layout on iPhone X. See screenshots below.

Screen Shot 2020-04-18 at 10 42 15 AM

Screen Shot 2020-04-18 at 10 42 41 AM

### PR DESCRIPTION
**Pull request by vijaysharwar**
Looks like some merge conflict resolution snuck older markup back. In this PR:

- Removed width/height attributes in `BarChart` svg
- Removed unnecessary wrapper divs around `BarChart` and `HorizontalBarChart`

Fixes #644. Regression issues will be fully resolved with the additional merge of https://github.com/COVID19Tracking/website/pull/641.

## Before

Screen Shot 2020-04-18 at 10 42 15 AM

Screen Shot 2020-04-18 at 10 42 41 AM

## After

Screen Shot 2020-04-20 at 2 59 43 PM

Screen Shot 2020-04-20 at 3 00 17 PM

### CODE REVIEW

File: src/components/charts/bar-chart.js [hunk 1]
```diff
@@ -43,68 +43,61 @@ const BarChart = ({
   )
 
   return (
-    <div align={align}>
```
Comment (jeremiak) [inline src/components/charts/bar-chart.js:46]: I had not idea that `align` was even a valid attribute for `<div>` elements! Did a bit of research and it looks like [MDN/caniuse](https://caniuse.com/#feat=mdn-html_elements_div_align) says that this attribute is deprecated and shouldn't be used. Noting for posterity

File: src/components/charts/horizontal-bar-chart.js [hunk 2]
```diff
@@ -31,57 +31,55 @@ export default function HorizontalBarChart({
...
-        </g>
-      </svg>
-    </div>
+          </g>
+        ))}
+      </g>
+
+      <g transform={`translate(0, ${marginTop})`}>
+        {data.map(d => (
+          <svg
```
Comment (jeremiak) [inline src/components/charts/horizontal-bar-chart.js:58]: Why embed another `<svg>` inside of the existing `<svg>`?

File: src/components/charts/bar-chart.js (hunk 1 above)
Comment (vijaysharwar) [reply src/components/charts/bar-chart.js:46]: Yeah, I didn't think we should use it, and the layout is now handled by classes with flexbox.

File: src/components/charts/horizontal-bar-chart.js (hunk 2 above)
Comment (vijaysharwar) [reply src/components/charts/horizontal-bar-chart.js:58]: Having the nested element allowed me to keep the containers left aligned, but text right justified with `textAnchor="end"`. Was [following example here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor).

From what I've read, nesting `<svg>` is allowable, and helps mimic relative positioning:

https://www.sarasoueidan.com/blog/nesting-svgs/
http://tutorials.jenkov.com/svg/svg-element.html

I tried using a `<g>` element but it clobbered the layout, stopped honoring the y position, and I couldn't figure out why:

Screen Shot 2020-04-20 at 4 37 05 PM

Since `<svg>` worked, I left it at that. But welcome other ideas!

Comment (jeremiak) [reply src/components/charts/horizontal-bar-chart.js:58]: Oh, woah! Thanks for pointing me towards this, that's a pretty powerful technique I had no idea about.
